export const START_TEXT_QUERY = "START_TEXT_QUERY";
export const START_TEXT_QUERY_SUCCESS = "START_TEXT_QUERY_SUCCESS";
export const START_TEXT_QUERY_FAIL = "START_TEXT_QUERY_FAIL";

export const START_EVENT_QUERY = "START_EVENT_QUERY";
export const START_EVENT_QUERY_SUCCESS = "START_EVENT_QUERY_SUCCESS";
export const START_EVENT_QUERY_FAIL = "START_EVENT_QUERY_FAIL";

export const STORE_USER_MESSAGE = "STORE_USER_MESSAGE";
